CREATE VIEW Post 
  (T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME)
AS
  SELECT T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME
    FROM T_CATERER JOIN T_CONTACT
    ON T_CATERER.ID_CATERER = T_CONTACT.ID_CATERER;


SELECT * FROM Post;


INSERT INTO Post
  (T_CATERER.NAME, T_CONTACT.NAME, T_CONTACT.SURNAME)
  VALUES
  ('Поставщик', 'Имя', 'Фамилия');


DELETE FROM Post
  WHERE ID_CATERER = 1;


UPDATE Post
  SET T_CONTACT.NAME = 'ALEX'
    WHERE ID_CATERER = 5;





