CREATE VIEW SURPLUS
  (MATERIAL, STORE, VOLUME)
AS
  SELECT T_MATERIAL.NAME, T_STORE.NAME, SUM(T_SURPLUS.VOLUME)
    FROM T_MATERIAL JOIN T_SURPLUS  
      ON T_MATERIAL.ID_MATERIAL = T_SURPLUS.ID_MATERIAL
    JOIN T_STORE 
      ON T_SURPLUS.ID_STORE = T_STORE.ID_STORE
    GROUP BY T_MATERIAL.NAME, T_STORE.NAME;


