CREATE VIEW STOREV
  (STORE, MATERIAL, MESSURE, SUMM)
AS
  SELECT T_STORE.NAME, T_MATERIAL.NAME, T_MESSURE.NAME,
         SUM(T_DELIVER.VOLUME)
    FROM T_DELIVER JOIN T_STORE 
      ON T_DELIVER.ID_STORE = T_STORE.ID_STORE    
    JOIN T_MATERIAL 
      ON T_DELIVER.ID_MATERIAL = T_MATERIAL.ID_MATERIAL
    JOIN T_MESSURE 
      ON T_MATERIAL.ID_MESSURE = T_MESSURE.ID_MESSURE
    WHERE DELIVER_DATE BETWEEN '01.01.2017' AND '31.12.2017'
  GROUP BY T_STORE.NAME, T_MATERIAL.NAME, T_MESSURE.NAME;
