CREATE TABLE t_CONTACT (
  ID_CONTACT INT NOT NULL PRIMARY KEY,
  SURNAME NVARCHAR2(150) NOT NULL ,
  NAME NVARCHAR2(150) NOT NULL ,
  FATHER_NAME NVARCHAR2(150) NOT NULL ,
  phone NVARCHAR2(150) NOT NULL
)