SELECT T_CATERER.NAME, T_MATERIAL.NAME, T_DELIVER.DELIVER_DATE, T_MATERIAL.KOLVO,T_MATERIAL.PRICE
  FROM T_CATERER, T_MATERIAL,T_DELIVER
    WHERE ((T_DELIVER.DELIVER_DATE>='01.01.2016' AND T_DELIVER.DELIVER_DATE<='31.07.2016') AND T_CETERER.CITY= 'Perm')