UPDATE T_EMPLOYER
  SET ID_MANAGER=NULL
    WHERE ID_EMPLOYER='1';

UPDATE T_EMPLOYER
  SET ID_MANAGER='1'
    WHERE ID_EMPLOYER='2';

UPDATE T_EMPLOYER
  SET ID_MANAGER='1'
    WHERE ID_EMPLOYER='3';

UPDATE T_EMPLOYER
  SET ID_MANAGER='1'
    WHERE ID_EMPLOYER='4';

UPDATE T_EMPLOYER
  SET ID_MANAGER='3'
    WHERE ID_EMPLOYER='5'

     