SELECT name FROM T_MATERIAL
WHERE ID_MATERIAL IN(
  SELECT T_DELIVER.ID_MATERIAL FROM T_DELIVER
  WHERE DELIVER_DATE BETWEEN '01.01.2009' AND '31.12.2009')
AND ID_MATERIAL IN (
  SELECT T_SURPLUS.ID_MATERIAL FROM T_SURPLUS
  WHERE VOLUME = '0' OR VOLUME IS NOT NULL)